import fs from "node:fs/promises";
import path from "node:path";
import { discoverLayouts } from "./discover.js";

function ident(name: string): string {
  return name.replace(/[^A-Za-z0-9_$]/g, "_");
}

// Emits a `PdfTemplateProps` interface mapping each template name to its
// inferred Vue props type. `ComponentProps` (vue-component-type-helpers) reads
// the real prop types from the SFC, so consumers get full type-checking on
// `generatePdf(template, data)` — provided they type-check with `vue-tsc`.
export async function generateTypes(
  templatesDir: string,
  outFile: string,
): Promise<void> {
  const disc = await discoverLayouts(templatesDir);
  const names = Object.keys(disc.entries).sort();

  const from = path.dirname(outFile);
  const imports = names
    .map((name) => {
      const rel = path
        .relative(from, disc.entries[name])
        .split(path.sep)
        .join("/");
      const spec = rel.startsWith(".") ? rel : `./${rel}`;
      return `import ${ident(name)} from ${JSON.stringify(spec)};`;
    })
    .join("\n");

  const map = names
    .map((name) => `  ${JSON.stringify(name)}: ComponentProps<typeof ${ident(name)}>;`)
    .join("\n");

  const content = `// AUTO-GENERATED by @hshm/vuedf — do not edit by hand.
// Regenerate with \`pdf-kit types\` or on every \`vite build\`.
import type { ComponentProps } from "vue-component-type-helpers";
${imports}

export interface PdfTemplateProps {
${map}
}
`;

  await fs.mkdir(from, { recursive: true });
  await fs.writeFile(outFile, content);
}
