[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.27.0"
ci = "github"
installers = ["shell"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
install-path = "CARGO_HOME"
install-updater = false
