import fs from "node:fs/promises";
import path from "node:path";
import { discoverLayouts } from "./discover.js";

function ident(name: string): string {
  return name.replace(/[^A-Za-z0-9_$]/g, "_");
}

// Emits a `VuedoProps` interface mapping each body template name to the
// exact data shape `generatePdf(name, data)` expects.
//
// React templates can use two conventions:
// 1. File-based: x.tsx (body), x-header.tsx (header), x-footer.tsx (footer)
// 2. Single-file: x.tsx exports named Body, Header, Footer components
//
// For single-file templates (no file-based aux), we use a `SectionProps`
// conditional type helper that safely accesses possibly-missing named exports.
// When an export doesn't exist, the section type resolves to `never` but
// remains optional, so the consumer can simply omit it.
export async function generateTypes(
  templatesDir: string,
  outFile: string,
): Promise<void> {
  const disc = await discoverLayouts(templatesDir);
  const bodies = Object.keys(disc.layouts).sort();

  const from = path.dirname(outFile);

  const layouts: Array<{
    bodyName: string;
    bodyFile: string;
    hasFileHeader: boolean;
    headerFile: string | null;
    headerExport: string;
    hasFileFooter: boolean;
    footerFile: string | null;
    footerExport: string;
  }> = [];

  for (const bodyName of bodies) {
    const layout = disc.layouts[bodyName];
    const bodyFile = disc.entries[layout.body];

    const hasFileHeader = !!layout.header;
    const hasFileFooter = !!layout.footer;

    layouts.push({
      bodyName,
      bodyFile,
      hasFileHeader,
      headerFile: hasFileHeader ? disc.entries[layout.header!] : null,
      headerExport: "Header",
      hasFileFooter,
      footerFile: hasFileFooter ? disc.entries[layout.footer!] : null,
      footerExport: "Footer",
    });
  }

  // Collect unique import paths (body files + separate aux files)
  const importMap = new Map<string, string>(); // filePath -> importAlias
  for (const l of layouts) {
    if (!importMap.has(l.bodyFile)) {
      importMap.set(l.bodyFile, ident(l.bodyName));
    }
    if (l.hasFileHeader && l.headerFile && !importMap.has(l.headerFile)) {
      importMap.set(l.headerFile, ident(l.bodyName) + "_header");
    }
    if (l.hasFileFooter && l.footerFile && !importMap.has(l.footerFile)) {
      importMap.set(l.footerFile, ident(l.bodyName) + "_footer");
    }
  }

  const imports = [...importMap.entries()]
    .sort(([, a], [, b]) => a.localeCompare(b))
    .map(([filePath, alias]) => {
      const spec = path.relative(from, filePath).split(path.sep).join("/");
      const relSpec = spec.startsWith(".") ? spec : `./${spec}`;
      return `import type * as ${alias} from ${JSON.stringify(relSpec)};`;
    })
    .join("\n");

  const map = layouts
    .map((l) => {
      const bodyImport = importMap.get(l.bodyFile)!;

      const headerType = l.hasFileHeader
        ? `ComponentPropsWithoutRef<typeof ${importMap.get(l.headerFile!)}["${l.headerExport}"]>`
        : `SectionProps<typeof ${bodyImport}, "Header">`;

      const footerType = l.hasFileFooter
        ? `ComponentPropsWithoutRef<typeof ${importMap.get(l.footerFile!)}["${l.footerExport}"]>`
        : `SectionProps<typeof ${bodyImport}, "Footer">`;

      const fields: string[] = [];
      fields.push(`    header?: ${headerType};`);
      fields.push(`    body: ComponentPropsWithoutRef<typeof ${bodyImport}["Body"]>;`);
      fields.push(`    footer?: ${footerType};`);
      fields.push(`    options?: GeneratePdfOptions;`);
      return `  ${JSON.stringify(l.bodyName)}: {\n${fields.join("\n")}\n  };`;
    })
    .join("\n");

  const content = `// AUTO-GENERATED by @vuedo/react — do not edit by hand.
// Regenerate with \`vuedo types\` or on every \`vite build\`.
import type { ComponentPropsWithoutRef } from "react";
import type { GeneratePdfOptions } from "@vuedo/react";

type SectionProps<M, K extends string> = K extends keyof M
  ? ComponentPropsWithoutRef<M[K]>
  : never;

${imports}

export type VuedoProps = {
${map}
};
`;

  await fs.mkdir(from, { recursive: true });
  await fs.writeFile(outFile, content);
}
