import fs from "node:fs/promises";
import path from "node:path";
import { discoverLayouts } from "./discover.js";

function ident(name: string): string {
  return name.replace(/[^A-Za-z0-9_$]/g, "_");
}

// Emits a `PandafProps` interface mapping each body template name to the
// exact data shape `generatePdf(name, data)` expects:
//   { header?, body, footer?, options }
// `header`/`footer` keys are present ONLY when the template actually has a
// paired aux (file-based layout convention), so the call is type-checked
// against precisely the sections that exist. `options` is always present and
// carries the Gotenberg margins. `ComponentProps` (vue-component-type-helpers)
// reads the real prop types from each SFC, so the whole thing is accurate
// provided consumers type-check with `vue-tsc`.
export async function generateTypes(
  templatesDir: string,
  outFile: string,
): Promise<void> {
  const disc = await discoverLayouts(templatesDir);
  const bodies = Object.keys(disc.layouts).sort();

  const from = path.dirname(outFile);

  // Every SFC we need to import: each layout's body + paired header + footer.
  const needed = new Set<string>();
  for (const bodyName of bodies) {
    const layout = disc.layouts[bodyName];
    needed.add(layout.body);
    if (layout.header) needed.add(layout.header);
    if (layout.footer) needed.add(layout.footer);
  }

  const imports = [...needed]
    .sort()
    .map((name) => {
      const rel = path
        .relative(from, disc.entries[name])
        .split(path.sep)
        .join("/");
      const spec = rel.startsWith(".") ? rel : `./${rel}`;
      return `import ${ident(name)} from ${JSON.stringify(spec)};`;
    })
    .join("\n");

  const map = bodies
    .map((bodyName) => {
      const layout = disc.layouts[bodyName];
      const fields: string[] = [];
      if (layout.header)
        fields.push(`  header: ComponentProps<typeof ${ident(layout.header)}>;`);
      fields.push(`  body: ComponentProps<typeof ${ident(layout.body)}>;`);
      if (layout.footer)
        fields.push(`  footer: ComponentProps<typeof ${ident(layout.footer)}>;`);
      fields.push(`  options?: GeneratePdfOptions;`);
      return `  ${JSON.stringify(bodyName)}: {\n${fields.join("\n")}\n  };`;
    })
    .join("\n");

  const content = `// AUTO-GENERATED by @pandaf/vue — do not edit by hand.
// Regenerate with \`pandaf types\` or on every \`vite build\`.
import type { ComponentProps } from "vue-component-type-helpers";
import type { GeneratePdfOptions } from "@pandaf/vue";
${imports}

export type PandafProps = {
${map}
};
`;

  await fs.mkdir(from, { recursive: true });
  await fs.writeFile(outFile, content);
}
