import { describe, it, expect, afterAll } from "vitest";
import { app, pdfKit } from "../src/server";

// Consumer tests (§7): plain requests against the app's own router. No network
// hop to mock — pdf-kit renders in-process; ?preview=html avoids Gotenberg.
const post = (body: unknown, qs = "") =>
  app.handle(
    new Request(`http://localhost/api/v1/generate-pdf${qs}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body),
    }),
  );

afterAll(() => pdfKit.close());

describe("service POST /api/v1/generate-pdf", () => {
  it("composes body + paired header/footer via ?preview=html (no Gotenberg)", async () => {
    const res = await post(
      { template: "Invoice", data: { id: "X1", customerName: "Acme Corp" } },
      "?preview=html",
    );
    const html = await res.text();
    expect(res.headers.get("content-type")).toContain("text/html");
    expect(html).toContain("X1");
    expect(html).toContain("Acme Corp");
    // Auto-paired InvoiceHeader / InvoiceFooter from the file convention.
    expect(html).toContain("vuedo inc.");
    expect(html).toContain("generated by vuedo");
    expect(html).toContain('class="vuedo-header"');
    expect(html).toContain('class="vuedo-footer"');
  });

  it("returns 422 on an invalid body", async () => {
    const res = await post({ nope: true });
    expect(res.status).toBe(422);
  });
});
