import { describe, it, expect } from "vitest";
import { app } from "../src/server";

// `app` is the single Elysia instance from src/server.ts (dev branch: Vite
// SSR render is wired at boot). The HTTP layer is driven via app.handle.
describe("buildApp /generate-pdf", () => {
  it("returns composed HTML via ?preview=html without hitting Gotenberg", async () => {
    const res = await app.handle(
      new Request("http://localhost/api/v1/generate-pdf?preview=html", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ template: "Invoice", data: { id: "X1" } }),
      }),
    );

    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("text/html");
    const text = await res.text();
    expect(text).toContain("<!DOCTYPE html>");
    expect(text).toContain("Invoice #X1");
  });

  it("rejects malformed bodies via TypeBox validation", async () => {
    const res = await app.handle(
      new Request("http://localhost/api/v1/generate-pdf", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ foo: "bar" }),
      }),
    );

    expect(res.status).toBe(422);
  });

  it("composes header and footer into the ?preview=html response", async () => {
    const res = await app.handle(
      new Request("http://localhost/api/v1/generate-pdf?preview=html", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          template: "Invoice",
          data: { id: "X2" },
          header: { template: "InvoiceHeader", data: {} },
          footer: { template: "InvoiceFooter", data: {} },
        }),
      }),
    );

    expect(res.status).toBe(200);
    const text = await res.text();
    expect(text).toContain("Invoice #X2");
    expect(text).toContain("vuedo inc."); // header content
    expect(text).toContain("generated by vuedo"); // footer content
  });
});
