import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "node:child_process";
import pdfParse from "pdf-parse";

// §7 strategy: test `server.ts` with NODE_ENV=production against a real
// `dist/` build. The orchestration, bundling, and header/footer wiring are all
// real; the PDF is produced by a live Gotenberg container (Chromium) started
// from the compose file in `deploy/`. Run `docker compose -f deploy/docker-compose.yml up`
// (or set GOTENBERG_URL) before this suite — it is skipped automatically when
// Gotenberg is unreachable. The returned PDF is parsed with pdf-parse to
// assert on text content and page count, exactly as §7 describes.

process.env.NODE_ENV = "production";

const GOTENBERG_URL = process.env.GOTENBERG_URL || "http://localhost:3000";

// Connectivity probe (top-level await so describe.skipIf sees the result).
let gotenbergAvailable = false;
try {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 2000);
  await fetch(`${GOTENBERG_URL}/forms/chromium/convert/html`, {
    method: "POST",
    signal: ctrl.signal,
    body: new FormData(),
  });
  clearTimeout(timer);
  gotenbergAvailable = true;
} catch {
  gotenbergAvailable = false;
}

describe.skipIf(!gotenbergAvailable)(
  "PDF generation — production renderer path + real Gotenberg (E2E, §7)",
  () => {
    beforeAll(() => {
      // Real production build: bundle entry-server.ts -> dist/entry-server.js.
      execSync(
        "pnpm exec vite build --ssr src/entry-server.ts --outDir dist --logLevel error",
        { cwd: process.cwd(), stdio: "inherit" },
      );
    }, 120_000);

    it("renders body + header + footer and returns a real PDF", async () => {
      process.env.GOTENBERG_URL = GOTENBERG_URL;
      const { app } = await import("../src/server");

      const res = await app.handle(
        new Request("http://localhost/api/v1/generate-pdf", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            template: "Invoice",
            data: { id: "INV-HF-1", customerName: "Header Footer Co" },
            header: { template: "InvoiceHeader", data: {} },
            footer: { template: "InvoiceFooter", data: {} },
          }),
        }),
      );

      expect(res.status).toBe(200);
      expect(res.headers.get("content-type")).toBe("application/pdf");
      expect(res.headers.get("content-disposition")).toBe(
        'attachment; filename="Invoice.pdf"',
      );

      const buffer = Buffer.from(await res.arrayBuffer());
      const parsed = await pdfParse(buffer);

      expect(parsed.numpages).toBeGreaterThanOrEqual(1);
      expect(parsed.text).toContain("INV-HF-1");
      expect(parsed.text).toContain("Header Footer Co");
      // Header/footer wiring: Gotenberg rendered the extra HTML parts.
      expect(parsed.text).toContain("vuedo inc.");
      expect(parsed.text).toContain("generated by vuedo");
    });

    it("works without header/footer (body only)", async () => {
      process.env.GOTENBERG_URL = GOTENBERG_URL;
      const { app } = await import("../src/server");

      const res = await app.handle(
        new Request("http://localhost/api/v1/generate-pdf", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            template: "Invoice",
            data: { id: "INV-NO-HF", customerName: "Body Only" },
          }),
        }),
      );

      expect(res.status).toBe(200);
      expect(res.headers.get("content-type")).toBe("application/pdf");

      const buffer = Buffer.from(await res.arrayBuffer());
      const parsed = await pdfParse(buffer);
      expect(parsed.text).toContain("INV-NO-HF");
      // No header/footer parts were sent, so their text is absent.
      expect(parsed.text).not.toContain("vuedo inc.");
      expect(parsed.text).not.toContain("generated by vuedo");
    });
  },
);
