import { describe, it, expect } from "vitest";
import { render } from "../src/server";

// Lighter suite (§7): calls the dev branch's render logic directly via the
// exported `render` (Vite ssrLoadModule path) — no HTTP layer, no Gotenberg.
describe("render (dev branch — Vite ssrLoadModule, no build step)", () => {
  it("SSR-renders the Invoice template with provided data", async () => {
    const html = await render("Invoice", {
      id: "INV-0001",
      customerName: "Acme Corporation",
    });
    expect(html).toContain("INV-0001");
    expect(html).toContain("Acme Corporation");
  });

  it("renders header and footer templates (header/footer path, §7)", async () => {
    const header = await render("InvoiceHeader", {});
    const footer = await render("InvoiceFooter", {});
    expect(header).toContain("vuedo inc.");
    expect(footer).toContain("generated by vuedo");
  });
});
