<template>
  <div
    class="vuedo-footer text-xs text-gray-400 border-t border-gray-200 pt-2 mt-4 text-center"
  >
    Confidential — generated by vuedo for {{ customerName }}
  </div>
</template>

<script setup lang="ts">
defineProps<{ id: string; customerName: string }>();
</script>
